import { sha3_512 } from './hash.js';
import { stringify } from './oson/stringify.js';

/**
 * Returns a cache key generated by hashing the context and arguments using SHA3-512.
 * Used for memoization.
 *
 * @param self - The context ('this' value) to include in the hash calculation
 * @param args - The arguments to include in the hash calculation
 * @returns A SHA3-512 hash of the stringified context and arguments.
 */
export function getCacheKeyOfHash(self: unknown, args: unknown[]): string {
  return sha3_512(stringify([self, args]));
}

/**
 * Returns a cache key generated by stringifying the context and arguments.
 * Used for memoization.
 *
 * @param self - The context ('this' value) to be included in the stringification
 * @param args - The arguments to be included in the stringification
 * @returns The stringified context and arguments.
 */
export function getCacheKeyOfStringified(self: unknown, args: unknown[]): string {
  return stringify([self, args]);
}

/**
 * Returns an empty string to be used as a cache key.
 * Used when no specific cache key value is needed for memoization.
 *
 * @returns An empty string.
 */
export function getCacheKeyOfEmptyString(): string {
  return '';
}
