name: Merge wbfy
on:
  workflow_dispatch:
  schedule:
    - cron: 40 17,18 * * *
permissions:
  contents: write
  pull-requests: write
jobs:
  wbfy-merge:
    uses: WillBooster/reusable-workflows/.github/workflows/wbfy-merge.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
